apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-teams
  labels:
    app: iot-teams
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-teams
  template:
    metadata:
      labels:
        app: iot-teams
    spec:
      containers:
        - name: iot-teams
          image: sthanguy/iot-teams
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: connection-string
                  key: connection_string
                  optional: false
